language: cpp
dist: bionic
compiler: clang

addons:
  apt:
    packages:
    - clang-10
    - libstdc++-8-dev
    - libmemcached-dev
    - cmake
    - libopenmpi-dev

script: 
  - mkdir build && cd build
  - cmake ../
  - make
